name: CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: correia
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_project_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache uv & venv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-py3.12-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-py3.12-

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync dependencies (dev)
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        env:
          GROQ_API_KEY: gsk_fake_key_for_testing_only
          DATABASE_URL: postgresql+psycopg://correia:postgres@localhost:5432/ai_project_db
        run: |
          uv run pytest -v --cov=. --cov-report=term-missing --cov-report=html --cov-fail-under=80

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/